---

  - name: Start reciever containers
    docker_container:
      name: "{{ logstash_container_name }}"
      env: "LS_HEAP_SIZE={{ ls_heap }}"
      exposed_ports:
        - 5000
      published_ports:
        - 5000:5000
      volumes:
        - "{{ logstash_conf_dir }}/{{ logstash_conf_type }}:/config-dir"
        - "{{ logstash_host_patterns_dir }}:/config-dir/patterns"
        - "/var/log/machines/{{ logstash_container_name }}:/var/log"
      image: "logstash:{{ logstash_container_version }}"
      state: started
      pull: yes
      restart_policy: unless-stopped
      command: "logstash -f /config-dir"
    when: is_reciever and not is_filter

  - name: Start filter containers
    docker_container:
      name: "{{ logstash_container_name }}"
      env: "LS_HEAP_SIZE={{ ls_heap }}"
      volumes:
        - "{{ logstash_conf_dir }}/{{ logstash_conf_type }}:/config-dir"
        - "{{ logstash_host_patterns_dir }}:/config-dir/patterns"
        - "/var/log/machines/{{ logstash_container_name }}:/var/log"
      image: "logstash:{{ logstash_container_version }}"
      state: started
      pull: yes
      restart_policy: unless-stopped
      command: "logstash -f /config-dir"
    when: is_filter and not is_reciever
