---

    - name: Get and start Elasticsearch container
      docker:
        name: "nginx"
        hostname: "{{ hostvars[inventory_hostname]['inventory_hostname'] }}"
        image: "nginx:{{ nginx_container_version }}"
        expose:
          - "80"
        ports:
          - "80:80"
        volumes:
          - /etc/hosts:/etc/hosts
          - "{{ nginx_conf_dir }}:{{ nginx_cont_dir }}"
        state: running
        pull: always
        restart_policy: unless-stopped
