---

    - name: Get and start Elasticsearch container
      docker_container:
        name: "nginx"
        hostname: "{{ hostvars[inventory_hostname]['inventory_hostname'] }}"
        image: "nginx:{{ nginx_container_version }}"
        exposed_ports:
          - "80"
        published_ports:
          - "80:80"
        volumes:
          - /etc/hosts:/etc/hosts
          - "{{ nginx_conf_dir }}:{{ nginx_cont_dir }}"
        state: started
        pull: yes
        restart_policy: unless-stopped
