---

  - include: installation-docker.yml
  - include: ensure-dirs.yml
  - include: remove-defaults.yml
    when: not keep_only_specified
  - include: remove-extras.yml
    when: keep_only_specified
  - include: remove-unwanted.yml
  - include: configuration.yml
