---

  - name: Setup HAproxy container
    docker:
      name: haproxy
      image: "haproxy:{{ haproxy_version }}"
      hostname: "{{ hostvars[inventory_hostname]['inventory_hostname'] }}"
      state: running
      pull: always
      volumes:
        - /etc/hosts:/etc/hosts
        - "{{ config_location }}:/usr/local/etc/haproxy/haproxy.cfg"
      expose:
        - 8077
        - 6672
      ports:
        - 8077:8077
        - 6672:6672
      restart_policy: unless-stopped

  - name: Create haproxy docker upstart script
    template:
      src: haproxy-upstart.conf.j2
      dest: "/etc/init/haproxy-{{ hostvars[inventory_hostname]['inventory_hostname'] }}.conf"
      owner: "root"
      group: "root"
      mode: 0775

  - name: Enable haproxy-docker upstart service
    service:
      name: "haproxy-{{ hostvars[inventory_hostname]['inventory_hostname'] }}"
      enabled: yes
      state: started
