---

  - name: Include os-specific variables
    include_vars: "{{ ansible_os_family }}.yml"

  - include: debian.yml
    when: ansible_os_family == "Debian"

  - include: redhat.yml
    when: ansible_os_family == "RedHat"
