---
- name: enable plugins
  rabbitmq_plugin:
    names: "{{ rabbitmq_plugins | join(',') }}"
    new_only: "{{ rabbitmq_new_only }}"
  notify: restart rabbitmq-server
  when: rabbitmq_plugins != []

- name: get the list of active plugins to disable
  command: rabbitmq-plugins list -e -m
  register: result
  when: rabbitmq_plugins == []
