---

  - name: Create Kibana dirs
    file:
      name: "{{ kibana_path }}/config"
      state: directory

  - name: set Kibana configuration
    template:
      src: "{{ kibana_vars_dir }}/kibana4.yml.j2"
      dest: "{{ kibana_path }}/config/kibana.yml"
      mode: 0755
    notify: restart kibana service

  - name: Setup Kibana container
    docker_container:
      name: kibana
      image: "kibana:{{ kibana_major_version }}"
      hostname: "kibana-{{ hostvars[inventory_hostname]['inventory_hostname'] }}"
      state: started
      pull: yes
      env:
        ELASTICSEARCH_URL: "http://{{ hostvars[groups['elasticsearch_masters'][0]]['ansible_template_host'] }}:9200"
      volumes:
        - /etc/hosts:/etc/hosts
        - "{{ kibana_path }}/config/kibana.yml:/etc/kibana/kibana.yml"
      exposed_ports:
        - 5601
      published_ports:
        - 5601:5601
      restart_policy: unless-stopped


  - name: Create kibana-docker upstart script
    template:
      src: "{{ kibana_vars_dir }}/kibana-upstart.conf.j2"
      dest: "/etc/init/kibana.conf"
      owner: "root"
      group: "root"
      mode: 0775

  - name: Enable logstash-docker upstart service
    service:
      name: kibana
      enabled: yes
      state: started
