---

  - name: create destination directory
    file: path={{ kibana_path }} owner=root group=root mode=0755 state=directory
    tags: [kibana]

  - include: kibana.yml
    tags: [kibana]

  - include: plugins.yml
    when: kibana_plugins is defined
    tags: [kibana]
