---

  - name: restart nginx
    docker_container:
      name: "nginx"
      hostname: "{{ hostvars[inventory_hostname]['inventory_hostname'] }}"
      image: "nginx:{{ nginx_container_version }}"
      restart: yes
      expose:
        - "80"
      ports:
        - "80:80"
      volumes:
        - /etc/hosts:/etc/hosts
        - "{{ nginx_conf_dir }}:{{ nginx_cont_dir }}"
      state: running
      pull: yes
      restart_policy: always
    changed_when: True

  - name: reload nginx
    docker_container:
      name: "nginx"
      hostname: "{{ hostvars[inventory_hostname]['inventory_hostname'] }}"
      image: "nginx:{{ nginx_container_version }}"
      restart: yes
      expose:
        - "80"
      ports:
        - "80:80"
      volumes:
        - /etc/hosts:/etc/hosts
        - "{{ nginx_conf_dir }}:{{ nginx_cont_dir }}"
      state: running
      pull: yes
      restart_policy: always
    changed_when: True
