---

  - name: restart nginx
    docker_container:
      name: "nginx"
      hostname: "{{ hostvars[inventory_hostname]['inventory_hostname'] }}"
      image: "nginx:{{ nginx_container_version }}"
      restart: yes
      expose:
        - "80"
      ports:
        - "80:80"
      volumes:
        - /etc/hosts:/etc/hosts
        - "{{ nginx_conf_dir }}:{{ nginx_cont_dir }}"
      state: started
      pull: yes
      restart_policy: always
      force_kill: yes

  - name: reload nginx
    docker_container:
      name: "nginx"
      hostname: "{{ hostvars[inventory_hostname]['inventory_hostname'] }}"
      image: "nginx:{{ nginx_container_version }}"
      restart: yes
      expose:
        - "80"
      ports:
        - "80:80"
      volumes:
        - /etc/hosts:/etc/hosts
        - "{{ nginx_conf_dir }}:{{ nginx_cont_dir }}"
      state: started
      pull: yes
      restart_policy: always
      force_kill: yes
