---

  - name: Set timezone variables
    copy: >
          content='{{ timezone }}\n'
          dest=/etc/timezone
          owner=root
          group=root
          mode=0644
          backup=yes
    notify:
      - update timezone
