# - name: Set Time Zone on Ubuntu <= 15.10
  tasks:
    - name: Set timezone variables
      copy: >
            content='{{ timezone }}\n'
            dest=/etc/timezone
            owner=root
            group=root
            mode=0644
            backup=yes
      notify:
        - update timezone
  handlers:
    - name: update timezone
      command: dpkg-reconfigure --frontend noninteractive tzdata
# - name: Set timezone to UTC
#   when: ansible_date_time.tz != '{{ timezone }}'
#   command: timedatectl set-timezone {{ timezone }}
