---
galaxy_info:
  author: Emiliano Castagnari
  description: Ansible role for FileBeat
  license: Apache
  min_ansible_version: 1.8
  platforms:
    - name: EL
      versions:
        - 6
        - 7
    - name: Debian
      versions:
        - wheezy
    - name: Ubuntu
      versions:
        - precise
        - trusty
    - name: Amazon Linux

  categories:
    - monitoring
    - system

dependencies: []
