---
  # handlers file for rabbitmq
  - name: restart rabbitmq-{{ hostvars[inventory_hostname]['inventory_hostname'] }}
    shell: docker restart rabbitmq-{{ hostvars[inventory_hostname]['inventory_hostname'] }}

  - name: delete guest
    rabbitmq_user:
      user: "guest"
      vhost: "/"
      state: absent
    run_once: true
    ignore_errors: true
