---

- name: Elastic APT Key
  apt_key: state=present url="{{ filebeat_apt_key }}"

- name : FileBeat APT Repository
  apt_repository: >
      state=present
      repo="deb {{ filebeat_apt_repository }} stable main"
      update_cache=yes

- name: Install FileBeat (Debian)
  apt: >
    state="{{ (filebeat_upgrade) | ternary('latest', 'present') }}"
    name="{{ item }}"
  with_items: "{{ filebeat_packages }}"
  notify: filebeat restart

- name: create certificates directory
  file: >
    path='{{ filebeat_certificates_dir }}'
    owner=root
    group=root
    mode=0640
    state=directory

- name: Adding user "{{ filebeat_user }} to adm group"
  user: name="{{ filebeat_user }}" groups=adm,syslog append=yes
  notify:
    - filebeat restart

# vi:ts=2:sw=2:et:ft=yaml
