---

  - name: detect installed plugins
    command: ls chdir={{ elastic_host_plugins_dir }}
    changed_when: False
    register: elasticsearch_register_installed_plugins

  - name: delete plugins
    shell: docker exec elastic-{{ hostvars[inventory_hostname]['inventory_hostname'] }} {{ elasticsearch_path_home }}/bin/plugin remove {{ item.name }}
    when: >
          item.delete is defined and item.delete and
          (item.name in elasticsearch_register_installed_plugins.stdout or
          item.name.split('/')[1].split('-')[1:] | join('-') in
          elasticsearch_register_installed_plugins.stdout)
    with_items: "{{ elasticsearch_plugins }}"
    notify:
       - restart elasticsearch

  - name: install plugins by name
    shell: docker exec elastic-{{ hostvars[inventory_hostname]['inventory_hostname'] }} {{ elasticsearch_path_home }}/bin/plugin install {{ item.name }}
    when: >
          (item.url is undefined or not item.url) and
          (item.delete is undefined or not item.delete) and
          not item.name.split('/')[1].split('-')[1:] | join('-') in
          elasticsearch_register_installed_plugins.stdout
    with_items: "{{ elasticsearch_plugins }}"
    notify:
       - restart elasticsearch

  - name: install plugins by url
    shell: >
          docker exec elastic-{{ hostvars[inventory_hostname]['inventory_hostname'] }} {{ elasticsearch_path_home }}/bin/plugin install {{ item.name }} -u {{ item.url }}
    when: >
          item.url is defined and item.url and
          (item.delete is undefined or not item.delete) and
          not item.name in elasticsearch_register_installed_plugins.stdout
    with_items: "{{ elasticsearch_plugins }}"
    notify:
       - restart elasticsearch

  - name: install core plugins
    shell: docker exec elastic-{{ hostvars[inventory_hostname]['inventory_hostname'] }} {{ elasticsearch_path_home }}/bin/plugin install {{ item }}
    when: >
          (not "{{ item }}" in  elasticsearch_register_installed_plugins.stdout)
           and install_core_plugins
    with_items: "{{ elasticsearch_core_plugins }}"
    notify:
       - restart elasticsearch
