---
    logstash_combined_configs:
        - syslog
        - authlog
        - nginx

    logstash_patterns:
        - grok-patterns
        - linux-syslog
        - nginx

    outputs_to_install:
        - output-authlog
        - output-syslog
        - output-nginx

    timezone: "Europe/Simferopol"

    logstash_endpoint_host_ip: "127.0.0.1:9200"
