---

  - name: remove apache default config
    file:
      path: /etc/httpd/conf.d/welcome.conf
      state: absent
    notify:
      - restart apache

  - name: Create librenms apache logs
    file:
      path: "{{ item }}"
      state: file
      owner: librenms
      group: apache
      setype: httpd_log_t
      mode: 0644
    with_items:
      - "{{ librenms_path }}/logs/access_log"
      - "{{ librenms_path }}/logs/error_log"

  - name: Template apache configuration
    template:
      src: librenms.conf.j2
      dest: /etc/httpd/conf.d/librenms.conf
      owner: apache
      group: apache
      backup: yes
    notify:
      - restart apache

  - name: Enable and start httpd
    service: name=httpd enabled=yes state=started
