---

  - name: install prerequisites
    apt: name={{ item }} state=installed
    with_items: "{{ librenms_packages }}"

  - name: enable php modules
    command: php5enmod mcrypt

  - name: disable apache site
    command: a2dissite 000-default

  - name: enable apache modules
    command: a2enmod rewrite
    notify: restart apache

  - name: Template rrdcached configuration
    template:
      src: rrdcached.j2
      dest: /etc/default/rrdcached
      owner: root
      group: root
      backup: yes
    notify:
      - restart apache

  - name: Create librenms directories
    file:
      path: /var/run/rrdcached
      state: directory
      owner: librenms
      group: librenms
      mode: 777
